#!/usr/bin/env python3
"""Generate 3D bodies for the footprints KiCad ships without one.

Four sensors on this board - two ICM-42688 IMUs, the BMP388 barometer and
the ICM-20948 - use LGA footprints that KiCad's 3D library does not cover.
In the render they appear as bare pads, which is fine for DRC and useless
for checking the module actually fits under the next board in the stack.

An LGA package is a rectangular block. So the body is generated as one, and
the dimensions are read from each footprint's OWN F.Fab outline rather than
typed in from a datasheet - the Fab layer is the package body by definition,
so this cannot disagree with the footprint it is attached to. Height is the
one number the footprint does not carry, and comes from the datasheet.

VRML rather than STEP: it is a text format, KiCad's 3D viewer renders it
natively, and a generated STEP would be a much larger thing to get right for
no extra fidelity on a box.

    python hardware/tools/gen_3d_models.py

Writes hardware/jfox-fmu-v1/3dmodels/*.wrl
"""

import re
import sys
from pathlib import Path

import kicad_geom

REPO = Path(__file__).resolve().parents[2]
BOARD = REPO / "hardware" / "jfox-fmu-v1"
OUT = BOARD / "3dmodels"

KICAD = Path(r"C:\Users\Jetta\AppData\Local\Programs\KiCad\10.0")
STOCK = KICAD / "share" / "kicad" / "footprints"

# footprint -> (library, package height in mm, body colour)
#
# Heights are the datasheet maxima. They matter here for one reason: the
# tallest part on the top side sets the minimum standoff between boards in
# the stack, so a body that is too short reads as clearance that is not
# there.
# All three live in the project's own library - KiCad ships no footprint for
# any of them, which is why they have no 3D model either.
LOCAL = BOARD / "jfox-fmu.pretty"

BODIES = {
    "InvenSense_LGA-14_2.5x3mm_P0.5mm": (0.91, (0.15, 0.15, 0.17)),
    "InvenSense_LGA-10_2x2mm_P0.5mm":   (0.75, (0.15, 0.15, 0.17)),
    "Bosch_LGA-10_2x2mm_P0.5mm_LayoutBorder2x3y": (0.80, (0.20, 0.20, 0.22)),
}

VRML = """#VRML V2.0 utf8
# Generated by hardware/tools/gen_3d_models.py - do not edit by hand.
# Body outline taken from the footprint's own F.Fab layer; height from the
# datasheet. Units are 0.1 inch, which is what KiCad's VRML importer expects
# when the model is placed at scale 1.
Shape {
  appearance Appearance {
    material Material {
      diffuseColor %(r).3f %(g).3f %(b).3f
      specularColor 0.10 0.10 0.10
      shininess 0.25
    }
  }
  geometry IndexedFaceSet {
    coord Coordinate {
      point [
%(points)s
      ]
    }
    coordIndex [
      0 1 2 3 -1
      4 7 6 5 -1
      0 4 5 1 -1
      1 5 6 2 -1
      2 6 7 3 -1
      3 7 4 0 -1
    ]
    solid TRUE
  }
}
"""

# KiCad VRML models are authored in 0.1 inch units.
MM_PER_UNIT = 2.54


def fab_outline(path):
    """Package body extent from the F.Fab layer, in mm.

    Reads balanced s-expressions via kicad_geom rather than a windowed
    regex. A non-greedy regex stops at the FIRST ")", which for

        (fp_rect (start -1.5 -1.25) (end 1.5 1.25) ... (layer "F.Fab"))

    is the end of the start pair - so the layer test never sees the layer,
    every footprint looks like it has no Fab outline, and the tool reports
    that there is no package body to model. That is the third time this
    exact regex shape has produced a confident wrong answer on this board.
    The balanced-bracket reader exists precisely for it.
    """
    t = path.read_text(encoding="utf-8")
    xs, ys = [], []
    for tok in ("fp_line", "fp_rect", "fp_poly"):
        for e in kicad_geom.sexprs(t, tok):
            if not re.search(r'\(layer "F\.Fab"\)', e):
                continue
            for m in re.finditer(r'\((?:start|end|xy) '
                                 r'(-?[\d.]+) (-?[\d.]+)\)', e):
                xs.append(float(m.group(1)))
                ys.append(float(m.group(2)))
    if not xs:
        return None
    return min(xs), min(ys), max(xs), max(ys)


def box(x0, y0, x1, y1, h):
    """Eight corners of the body, in VRML units, seated on the board."""
    # KiCad's 3D frame is X right, Y UP out of the board, Z toward the
    # viewer - not the footprint's X/Y. Getting this wrong lays the part
    # flat against the board edge instead of on its face.
    def u(v):
        return v / MM_PER_UNIT
    pts = []
    for z in (u(y0), u(y1)):
        for x in (u(x0), u(x1)):
            pts.append((x, 0.0, z))
    # Reorder to a consistent winding: bottom face 0-3, top face 4-7.
    b = [pts[0], pts[1], pts[3], pts[2]]
    top = [(x, u(h), z) for x, _, z in b]
    return b + top


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for fp, (height, colour) in BODIES.items():
        src = LOCAL / f"{fp}.kicad_mod"
        if not src.exists():
            sys.exit(f"{src} not found - cannot derive a body from a "
                     f"footprint that is not there")
        ext = fab_outline(src)
        if ext is None:
            sys.exit(f"{fp}: no F.Fab outline, so there is no package body "
                     f"to model - refusing to invent one")
        x0, y0, x1, y1 = ext
        pts = box(x0, y0, x1, y1, height)
        r, g, b = colour
        body = VRML % {
            "r": r, "g": g, "b": b,
            "points": "\n".join("        %.4f %.4f %.4f," % p for p in pts),
        }
        dst = OUT / f"{fp}.wrl"
        dst.write_text(body, encoding="utf-8")
        written.append((fp, x1 - x0, y1 - y0, height))

    print(f"  wrote {len(written)} model(s) to "
          f"{OUT.relative_to(REPO)}")
    for fp, w, h, z in written:
        print(f"     {w:.2f} x {h:.2f} x {z:.2f} mm   {fp}")
    return written


if __name__ == "__main__":
    main()
